<!DOCTYPE html>
<html lang="en">
<head>
    
    <!-- [METATAGS] -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <!-- [TITLE] -->
    <title>SAMOPASTER - Sharing knowledge</title>
    
    <!-- [SHEETSTYLES] -->
    <link href="Attachments/sheetstyles/bootstrap.css" rel="stylesheet">
    <link href="Attachments/sheetstyles/config_min.css" rel="stylesheet">
 
    <!-- [JAVASCRIPT] -->
    <!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    <script src="Attachments/javascript/bootstrap.js"></script>

</head>

    <body>
    
        <div id="container">
        
            <div class="navbar">
                <div class="navbar-inner">
                <ul class="nav nav-pills pull-right">
                    <li><a href="home.html">Home</a></li>
                    <li class="active"><a href="about.html">About</a></li>
                    <li><a href="contact.html">Contact</a></li>
                </ul>
                <a class="brand" href="home.html">SAMOPASTER</a>
                </div>
            </div>

			<hr />


            <h4>About</h4>

            <p>The SAMOPASTER is web application that allows developers to upload snippets of text and examples of source code, for public viewing.</p>
            <p>All codes and texts published on this service are the sole responsibility of their authors, therefore if any Content that infringes any law or intellectual property and / or business, please contact us and to be immediately removed from the air.</p>


        </div>
        
        <script type="text/javascript">

		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-38177073-1']);
		  _gaq.push(['_trackPageview']);

		  (function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();

		</script>
        
        
    </body>

</html>