<!DOCTYPE html>
<html lang="en">
<head>
    
    <!-- [METATAGS] -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <!-- [TITLE] -->
    <title>SAMOPASTER - Sharing knowledge</title>
    
    <!-- [SHEETSTYLES] -->
    <link href="Attachments/sheetstyles/bootstrap.css" rel="stylesheet">
    <link href="Attachments/sheetstyles/config_min.css" rel="stylesheet">
    <link href="Attachments/sheetstyles/jquery.snippet.min.css" rel="stylesheet">
 
    <!-- [JAVASCRIPT] -->
    <!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
    <script type="text/javascript" src="Attachments/javascript/bootstrap.js"></script>
	<script type="text/javascript" src="Attachments/javascript/jquery.snippet.min.js"></script>

</head>

    <body>
    
        <div id="container">
        
            <div class="navbar">
                <div class="navbar-inner">
                <ul class="nav nav-pills pull-right">
                    <li><a href="home.html">Home</a></li>
                    <li><a href="about.html">About</a></li>
                    <li><a href="contact.html">Contact</a></li>
                </ul>
                <a class="brand" href="home.html">SAMOPASTER</a>
                </div>
            </div>

			<hr />


            <h4><?php echo $o_informations->code_title; ?></h4>
			<pre class="htmlCode"><?php echo htmlentities($o_informations->code_text, ENT_QUOTES, 'UTF-8'); ?></pre>
			
			<script>
			$(document).ready(function(){
				$("pre.htmlCode").snippet("html",{style:"emacs",transparent:true,});
			});
			</script>

        </div>
        
        <script type="text/javascript">

		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-38177073-1']);
		  _gaq.push(['_trackPageview']);

		  (function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();

		</script>
        
        
    </body>

</html>